manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 722a6f995fa4d6cc975b942bb9a225fba68746f7
      import: true

  self:
    path: zephcore
