manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: aef8f32f551421138276c0c818b4505233c372a4
      import: true

  self:
    path: zephcore
