manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 07a59810f8748ca08306d2b81bbe84c8c31c1a36
      import: true

  self:
    path: zephcore
