# Seeed SenseCAP Solar Node (P1 / P1-Pro)
# SPDX-License-Identifier: MIT
#
# SX1262 on SPI2 (P0.04 CS, P0.03 DIO1, P0.28 RST, P0.29 BUSY, P0.05 RXEN)
# Quectel L76K GNSS on UART0 9600 (P1.11/12), enable P1.05, reset P1.03
# QSPI P25Q16H 2MB; battery AIN7 + P0.14 divider enable (active low)

CONFIG_ZEPHCORE_BOARD_NAME="SenseCAP Solar"

CONFIG_BT_DIS_MODEL_NUMBER_STR="Seeed SenseCAP Solar"

CONFIG_ZEPHCORE_SD_FWID=0x0123
